### ISSUE TITLE
Invoke lambda before signIn

### ISSUE THREAD

**Issue by Shahmatist3** [awslabs/aws-sdk-ios-samples#115]
Hi!
I try to invoke lambda before signIn. 
But when i call it 

```
AWSLambdaInvoker *lambdaInvoker = [AWSLambdaInvoker LambdaInvokerForKey:@"kLambdaInvokerActivity"];
    [[lambdaInvoker invokeFunction:@"lambdaTest" continueWithBlock:^id(AWSTask *task) ...
```
it calls two delegate before 

1. -(id<AWSCognitoIdentityPasswordAuthentication>) startPasswordAuthentication
2. -(void) getPasswordAuthenticationDetails: (AWSCognitoIdentityPasswordAuthenticationInput *) authenticationInput  passwordAuthenticationCompletionSource: (AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> *) passwordAuthenticationCompletionSource 

And that's all. Without any task.

I set up two roles in Aws for my userPool (auth, unauth).
in Console "Enable access to unauthenticated identities" - OK

How should I call lambda?
thank you

**Comment by behrooziAWS** [comment]
If you want your call Lambda with an unauthenticated identity, you need to configure your AWSLambdaInvoker to use a AWSCognitoCredentialsProvider that does not specify your AWSCognitoIdentityUserPool as the identityProviderManager.  When you specify the AWSCognitoIdentityUserPool as the identityProviderManager it will always authenticate the user if they are not logged in.

Due to the fact that once an identity becomes authenticated, you can never use it without supplying credentials, if you are always trying to make an unauthenticated call to Lambda prior to signing in, you may need to use a completely different identity pool for this credentials provider.  If you don't, once you have authenticated once, you will never be able to use that identity as unauthenticated again.  If you keep your unauthenticated identities in a separate pool, you can continue to use them unauthenticated.

Alternatively, you could front your Lambda with an unauthenticated API Gateway api and use a simple rest call.

Depending on your use case, the pre-authentication lambda trigger may also help with what you are trying to do: http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html

**Comment by Shahmatist3** [comment]
@behrooziAWS Thank you for your advice. I separated pool for unauthenticated and authenticated user and it works.
