### ISSUE TITLE
library not found for -lPods-AWSCognito

### ISSUE THREAD

**Issue by Hemen** [awslabs/aws-sdk-ios-samples#16]
Hello,

Please help me out i have tried in all the way and i have tried to remove the cocoapods and reinstalled again now i am getting everything but library not found for -lPods-AWSCognito, Folder is already downloading for AWSCognito. Check the screenshot of Pods downloaded.
![screen shot 2015-07-07 at 3 15 34 pm](https://cloud.githubusercontent.com/assets/2232136/8543570/39032d98-24bb-11e5-85b8-1ac9925fe5dd.png)
![screen shot 2015-07-07 at 3 17 24 pm](https://cloud.githubusercontent.com/assets/2232136/8543593/56db0660-24bb-11e5-8e98-58ae8ab4018a.png)

**Comment by Hemen** [comment]
This is the same sample code i am trying but it is not building. Give me some suggestions so that i can able to run this sample code which is provided here.

**Comment by langtind** [comment]
Did you open the CognitoSyncDemo.xcworkspace? It looks as if you are trying to use CognitoSyncDemo.xcodeproj (which wouldn't work when using cocoapods).

**Comment by Hemen** [comment]
So What i need to do then ? Do i need to integrate by creating the new project ? How do i run this sample and get to know about the flow for the AWS?

**Comment by langtind** [comment]
It looks like you already have downloaded the example code and run "pod install" (in the CognitoSync-Sample/Objective-C-folder). For you to compile and test the example project all you need to do is to open the workspace (instead of the project). (In Finder open CognitoSyncDemo.xcworkspace, not CognitoSyncDemo.xcodeproj).
![skjermbilde 2015-07-07 12 53 21](https://cloud.githubusercontent.com/assets/90274/8544636/3eb2b4e8-24a7-11e5-996c-e2609c288cd3.png)

The example project requires you to make some changes to "Constants.m", but thats another topic.

**Comment by Hemen** [comment]
Hey, Damn Happy!!

Working find now.

Thanks a Lot :)
