### ISSUE TITLE
CognitoSync-Sample (Object C/ Swift ) compile error (Both)

### ISSUE THREAD

**Issue by paultwin0202** [awslabs/aws-sdk-ios-samples#169]
I am struggling with compile this sample application.

In terms of Object C, it shows compile error as following.

Even if I enable/disable bitcode, it fails to compile.

ld: '/Users/kimguyjoong/Documents/source/aws-sdk-ios-samples-master/CognitoSync-Sample/Objective-C/LoginWithAmazon.framework/LoginWithAmazon(AIMobileLib.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

For Swift, I think it is not comparable with Swift 3.0 yet.

What should I do for testing CognitoSync-Sample ?

**Comment by mrmcgrewx** [comment]
Hey paultwin0202,

As far as Swift 3 is concerned, after updating the syntax from the example Amazon provides I was able to compile and run the program successfully with no issues. Don't know much about objective-C but I had the same bitcode issue when using swift (although the error was from the google sdk, not the aws sdk like yours), I disabled bitcode as well but it would not compile for me until I restarted xcode, but I believe that was just a random Xcode bug since I usually do not need to restart Xcode. If you need assistance with any of the demo's running in Swift 3 just let me know.

**Comment by maxhuer** [comment]
Hi @mrmcgrewx 

xcode : 8.3.2
ios 10.3.2
objective c

I meet the same question about "linker command failed with exit code 1".
When i build with simulator, it is fine.
but if i build with NO SIMULATOR device, it can't build success.
Until i disable the bitcode , it is work.

**Comment by jhaoheng** [comment]
Hi @mrmcgrewx 

xcode : 8.3.2
ios 10.3.2
objective c
use cocoapod

I meet the same question about "linker command failed with exit code 1".
When i build with simulator, it is fine.
but if i build with NO SIMULATOR device, it can't build success.
Until i disable the bitcode , it is work.

**Comment by muellerfr** [comment]
Hello @paultwin0202,

Please use [AWS AppSync](https://aws.amazon.com/appsync/resources/) instead of Amazon Cognito Sync. Like Amazon Cognito Sync, AWS AppSync is a service for synchronizing application data across devices.

It enables user data like app preferences or game state to be synchronized. It also extends these capabilities by allowing multiple users to synchronize and collaborate in real time on shared data.

Please let us know if you have any questions about AppSync.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-android/issues if you are still encountering problems.
