### ISSUE TITLE
Lex Fails to voice recognize at very first Time 

### ISSUE THREAD

**Issue by Baalakrishnan** [awslabs/aws-sdk-ios-samples#232]
I tried to integrated voice integration, right now its working fine, but very first time always fails to recognize voice and also after wake up from the sleep it always fail for very first time, kindly provide me solution to sort out this issue

**Comment by kredden** [comment]
Hi, we will need some more details on exactly what the problem is you are having to be able to help.

Are you using the sample?  Which one and Swift or ObjC?  Have you made any modifications to it?  Have you put in any logging to try and figure out what is happening and if your code is getting called when you expect it to be?  Are you getting any errors?

Regards,
Kevin

**Comment by Baalakrishnan** [comment]
Hi,
I useing swift sample and my code also based on swift, while Enable the voice button and start to speak every first time its prompt says "sorry you can repeat that" for my bot, if I check with the text out put most of time it is empty or have the unrelated two char words, above issue smiler in both AWSLex sample and also our App

Thanks,
Balakrishnan

**Comment by kvasukib** [comment]
Hi @Baalakrishnan, Sorry for the delayed response. Do you still face the issue?

**Comment by Baalakrishnan** [comment]
Hi @kvasukib ,
Right now I am not using it for voice to Text, so I closing  this one now 

Thanks,
Balakrishnan J
