### ISSUE TITLE
FB login not authenticated by Federated Identity and User Pool

### ISSUE THREAD

**Issue by pothunoorisk** [awslabs/aws-sdk-ios-samples#236]
Hi Everyone,

I am integrating AWS with my iOS app for user sign in and sync. I have successfully implemented user sign up/sign in using user pool. Now I am integrating social providers sign ins with Federated IDs and User Pool. My code is in Objective C.

I have integrated FB and Google sign in with my app. It works well and I get tokens (FBAccessToken from FB). But this user is not getting authenticated in Federated IDs (It gives error message: 'Unauthenticated access is not supported for this identity pool.'). If I allow unauthenticated identities in my Fedreated ID setting, then this FB signed in user is shown as Unauthenticated Id in Federated ID, and obviously no related user in userPool.

How I implemented:
1. I have added Facebook in Authenticated Providers for Federated ID.
2. I have also added Facebook in Identity Providers for User Pool and done attributes mapping (mapped Id and Email).
3. I have created a social ID provider class which implements AWSIdentityProviderManager protocol. This class contains logins method as given:

- (AWSTask<NSDictionary<NSString *, NSString *> *> *)logins {
    NSLog(@"Inside logins method!");
    FBSDKAccessToken* fbToken = [FBSDKAccessToken currentAccessToken];
    if(fbToken){
        NSString *token = fbToken.tokenString;
        return [AWSTask taskWithResult: @{ AWSIdentityProviderFacebook : token }];
    } else {
        NSLog(@"FB Token is not found in AWSSocialIdentityProvider class");
        return [AWSTask taskWithError:[NSError errorWithDomain:@"facebook"
                                                          code:-1
                                                      userInfo:@{@"error":@"No current Facebook access token"}]];
    }
}

4. My Sign In View Controller does FB sign in. It creates fbCredentialsProvider by passing the socialIDProvider class as an identityProvider in it's construction, implemented as below:

        self.fbCredentialsProvider = [[AWSCognitoCredentialsProvider alloc] initWithRegionType:AWSRegionUSEast1 identityPoolId:@"us-east-1:XXXXXXXXXXXX" identityProviderManager:self.socialIDProvider];
        AWSServiceConfiguration *configuration = [[AWSServiceConfiguration alloc] initWithRegion:AWSRegionUSEast1 credentialsProvider:self.fbCredentialsProvider];
        [AWSServiceManager defaultServiceManager].defaultServiceConfiguration = configuration;
    
        //wipe cached credentials
        [self.fbCredentialsProvider clearKeychain];
        [self.fbCredentialsProvider clearCredentials];
    
        //For calling fb logins
        [self.fbCredentialsProvider credentials];

5. The above code is called in didCompleteWithResult method of FB Login Button.
That's it.

I know this question has been asked by many and there are many issues/answers on forums, and I have read (I suppose) almost all of them, but none could help in resolving the issue.

Please help here as I am stuck at this issue for over a month, read all the AWS documention on AWS-iOS SDK, number of articles, forums and yet could not resolve it. Now we cannot afford to loose more time and have to finish it sooner, so need help from AWS team/fellow developers.

If anyone can point error in the code (if any), and provide correct code will be highly appreciated.

Thank you in advance!

**Comment by Muthulakshmi1201** [comment]
hi 
can u send me the code for signingin .
could able to do signup successfully

**Comment by kvasukib** [comment]
Hi @pothunoorisk,

Have you followed the steps on Facebook here at https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-social.html ?

**Comment by johndpope** [comment]
So I got this working using the mobile hub https://console.aws.amazon.com/mobilehub/home generated sample under resources / you can spit out a full app. Albeit the sample app crashes without additional method for google sign in. See fix here
https://github.com/awslabs/aws-sdk-ios-samples/issues/246


Not sure what additional configuration is happening behind the scene. But you should get an aws Json file. Use this instead of manually configuring stuff and it will work.

**Comment by johndpope** [comment]
@pothunoorisk I got some feedback from Amazon regarding this - 

_This would only work if they use the Hosted UI: https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-ux.html
 
If they have their own UI, then logging in with FB/Google still requires that they create a hook to add that user to Cognito (which is a hack, btw, since the user won’t be able to login without a password).
 
So yes, this is possible but only with Hosted UI. 
 
They should review this video to get more details about the hosted UI: https://www.youtube.com/watch?v=VZqG7HjT2AQ
 
There’s a link to the app in the comments, which should get them started faster._

**Comment by johndpope** [comment]
if you create a url using this formula 
https://<your_domain>/login?response_type=code&client_id=<your_app_client_id>&redirect_uri=<your_callback_url>

you will see a page like this - 
![screen shot 2018-02-27 at 2 38 21 pm](https://user-images.githubusercontent.com/289994/36750577-e2d7e782-1bcb-11e8-8f44-752cb8f96fb3.png)


signing up here with facebook / google will create users in the user faecbook / google group pool.

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue in https://github.com/aws/aws-sdk-ios/issues if you are still encountering problems.
