### ISSUE TITLE
User Pools Suggestions

### ISSUE THREAD

**Issue by hmehran** [awslabs/aws-sdk-ios-samples#92]
Hey guys,
I didn't know where to leave a suggestion to I thought here would be a good place.
Good job so far on User pools. 
Two things that i noticed that bugged me were that you could make two user names that were essentially the same like "carrot" & "CarRot" and both would be counted as two distinct usernames. 
Secondly you can create two different accounts using the same email address and the system would allow it. And there is no option to disallow it. 

I know its still in beta so I tried to be light. 
Thanks for listening,
hm

**Comment by kushwahavinay** [comment]
Thanks for the suggestions! 
1) Currently username are case sensitive, but we can consider an option to make them case insensitive as a new feature for our future releases.
2) Currently by design same email can be used to create multiple accounts. You can explore alias option for this use case. Alias forces the confirmed email address to belong to a single account at a time and it can be used in place of username. See the alias section in Cognito [developer guide.](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-settings.html)

**Comment by caibojian** [comment]
CFNetwork SSLHandshake failed (-9829)
